### ISSUE TITLE
Editing notes

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#18]
This issue thread is to discuss specific editing conventions that we'll use in the paper. (Not substantive or economic issues in the manuscript, which are on other issue threads.)
Molly has done a great job getting us organized on this. 
In my edits so far this week, I have been using the following conventions:

1. Use "panel" instead of "subfigure," as I think it's more standard.
2. Changed “access” to “supply” because (i) supply is more standard econ word, and (ii) access seems to imply physical access, while supply accommodates other factors that we might have in mind, such a prices.
3. Use ”percent” instead of “%” except inside of equations.
4. Spell out all numbers less than 10, per standard convention.
5. Use “U.S.” always, not US, just cuz.
6. I know from painful experience that Larry Katz likes all footnotes at end of sentence, and no more than one footnote per sentence, so let's do that. 
7. I changed to census instead of Census; apologies for that weirdness before.
8. Either “nutritional inequality” or “nutrition-income relationship” are OK.
9. Commas after the thousands place, including in four-digit numbers. (Sorry and thanks JP.)
10. Product group, not product category, in the demand model
11. Product characteristic or dietary component, instead of nutrient, in the demand model, because it's a little weird to call "dairy" a nutrient given that we're now using HEI instead of the old ADD Health Index.

I hope that this is OK? And if so, let's all use these in future?

Tagging @mollyschnell @moosedube @diamondr @handbury @Rahkovsky

**Comment by moosedube** [comment]
I see we are now into the “super important” edits. 😉

Sent from my iPhone

On Oct 17, 2018, at 8:39 PM, Hunt Allcott <notifications@github.com<mailto:notifications@github.com>> wrote:


This issue thread is to discuss specific editing conventions that we'll use in the paper. (Not substantive or economic issues in the manuscript, which are on other issue threads.)
Molly has done a great job getting us organized on this.
In my edits so far this week, I have been using the following conventions:

  1.  Use "panel" instead of "subfigure," as I think it's more standard.
  2.  Changed “access” to “supply” because (i) supply is more standard econ word, and (ii) access seems to imply physical access, while supply accommodates other factors that we might have in mind, such a prices.
  3.  Use ”percent” instead of “%” except inside of equations.
  4.  Spell out all numbers less than 10, per standard convention.
  5.  Use “U.S.” always, not US, just cuz.
  6.  I know from painful experience that Larry Katz likes all footnotes at end of sentence, and no more than one footnote per sentence, so let's do that.
  7.  I changed to census instead of Census; apologies for that weirdness before.
  8.  Either “nutritional inequality” or “nutrition-income relationship” are OK.

I hope that this is OK? And if so, let's all use these in future?

Tagging @mollyschnell<https://github.com/mollyschnell> @moosedube<https://github.com/moosedube> @diamondr<https://github.com/diamondr> @handbury<https://github.com/handbury> @Rahkovsky<https://github.com/Rahkovsky>

**Comment by huntallcott** [comment]
@handbury @mollyschnell two very minor editing notes:
1. There was a question about the household size control. It's a continuous variable because it's in units of adult equivalents. I changed the text in 4.3 to make slightly clearer.
2. I changed "nutrition-income gradient" to "nutrition-income relationship" in 4.3
