### ISSUE TITLE
Get GitHub set up

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#2]
@diamondr @mollyschnell @handbury @moosedube @rakhkovs ,
The goal of this issue is to get GitHub set up on all of your local computers, so that you can modify code and eventually the lyx file. 
As of now you have a GitHub username and the dropbox folder (which has our data and other materials, but not the code or lyx file), but you may or may not have a git folder setup that has our code and lyx file.

To get set up:
1. Install GitHub desktop from here: [https://desktop.github.com](https://desktop.github.com)
2. Make sure there is a git folder on your computer that is outside of dropbox, e.g. mine is C:/Users/Hunt/Documents/GitHub.
3. Set up ("Clone") the GitHub repository (containing the code and lyx files) onto your computer by following the instructions at the very bottom of [this page](https://github.com/huntallcott/lab/wiki/Setup), under "Cloning GitHub repo to each team member's computer."
4. To re-download the code and lyx files later as people change them on the master repository in the cloud, and also to make changes yourself and push them to the master repository, follow the instructions at the top of [this page](https://github.com/huntallcott/lab/wiki/Software-Manuals).
5. Optional is to read the resources for learning git on [this same page](https://github.com/huntallcott/lab/wiki/Software-Manuals).

If you have questions or problems that others might have, you can post on this thread.

**Comment by Rahkovsky** [comment]
@huntallcott @diamondr @handbury @mollyschnell 
Hi, I changed my user name to @rahkovsky, sorry for confusion.

**Comment by huntallcott** [comment]
@diamondr @mollyschnell @handbury @Rahkovsky @moosedube ,
Quick minor note: it would be helpful to me if we all could continue using Lyx 2.2 for FoodDeserts.lyx. I'm having a bit of a computer bug and I won't be able to compile if we accidentally change it to Lyx 2.3 format, plus if one person moves to Lyx 2.3 then everyone else will have to use 2.3 because it's not backwards-compatible. 
So far we are OK but please make a mental note?

**Comment by moosedube** [comment]
Can it still be installed?  I no longer have that version as my other projects all upgraded.

Sent from my iPhone

On Aug 11, 2018, at 2:31 PM, Hunt Allcott <notifications@github.com<mailto:notifications@github.com>> wrote:


@diamondr<https://github.com/diamondr> @mollyschnell<https://github.com/mollyschnell> @handbury<https://github.com/handbury> @Rahkovsky<https://github.com/Rahkovsky> @moosedube<https://github.com/moosedube> ,
Quick minor note: it would be helpful to me if we all could continue using Lyx 2.2 for FoodDeserts.lyx. I'm having a bit of a computer bug and I won't be able to compile if we accidentally change it to Lyx 2.3 format, plus if one person moves to Lyx 2.3 then everyone else will have to use 2.3 because it's not backwards-compatible.
So far we are OK but please make a mental note?
