### ISSUE TITLE
Revise structural model

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#20]
The goal of this issue is to revise the structural model and writeup per QJE referee comments.
@diamondr, @moosedube, and I are talking today to get started.
Meeting notes for today are [here](https://docs.google.com/document/d/1udl84XM9icVlII5nwUTV1NtZmC8LyWZa5mZY5SCfHyc/edit?usp=sharing).

**Comment by huntallcott** [comment]
@moosedube thanks for your work on the text. Two questions:
1. Can 5.1 be entirely or mostly appendixed, and just start with something closer to the CES utility in what’s now Equation 6? I notice that there’s still some things there (script S, bold y, bold p, bold A, bold Theta, etc., plus continuity and concavity assumptions, etc.) that don't really add any intuition and are not used later in the paper.
2. Minor: p tilde and a tilde were never defined, so I added those definitions.

**Comment by moosedube** [comment]
On 5.1, we used to use this version of the model to make a connection between our structural model and the so-called “reduced-form” approach used for our entry event study, which does look at store choice as well.  That said, I agree that we don’t per se need this.  We could delete the paragraph starting “Each week” in section 5.1 and then go straight to 5.2 (i.e., combine the sections).  In the first paragraph of 5.1, we could then delete any notation we no longer use.

JP

**Comment by huntallcott** [comment]
Great, yes, @moosedube I would be in favor of that proposal.

**Comment by moosedube** [comment]
I noticed that the most recent version of the paper is now in Lyx 2.30.  Does this mean we no longer need to keep version 2.2 on our computers?  In the fall, I think you were having trouble getting 2.2 working on your computer.

**Comment by huntallcott** [comment]
Sorry, I just changed back to 2.2. Let's keep it there just to be safe.

**Comment by moosedube** [comment]
Uh oh … already uploaded the revised document with section 5.1 and 5.2 combined into a single short section.

JP

**Comment by huntallcott** [comment]
@moosedube I just re-did your revision in lyx 3.2.
@diamondr, just checking in. I know there was a lot of re-analysis to do here, but I just wanted to see how it's going!

**Comment by huntallcott** [comment]
@diamondr thanks for your great work on this, and @moosedube thanks for your edits over the weekend as well. 
@diamondr I have a couple of questions.
1. You have two nice suggestive tests of the exclusion restriction in 6.3. It occurs to me that both are really doing the same thing, as I suggest in my new proposed text:
*Of course, we cannot test whether the instrument is correlated with unobserved tastes. We can, however, present suggestive tests of whether the instrument is correlated with tastes predicted by observable characteristics. The economic forces that would violate the exclusion restriction would likely generate correlations between the instrument and both unobserved and predictable tastes. If the instrument is valid, we should thus expect to see no relationship between the instrument and predictable tastes. 
We implement two tests, each of which predicts tastes in a different way.*
In light of this close conceptual relationship between the two tests, shouldn't we unify the tests a bit more? In Table 4, I see that column 1 has P on the RHS and does not have county fixed effects, while column 2 has P on the LHS and does have county fixed effects but not time effects. I think it's helpful to have P on the RHS because \hat{Y} is fitted in column 1. So what if we:
a. Unify both columns by putting P on RHS and having j and and m fixed effects in all regressions. 
b. For further unification, why not use county income (continuous) instead of 1(above median) in column 2? I think the above median thing was a historical relic from when we were graphing something?
2. Closely related: what is the justification for having year FEs in column 1 but not column 2? I would have thought that both columns have the same issue, which is that county income and other taste predictors don't change much over time. So I would have thought we shouldn't have t fixed effects.
3. Shouldn't the X variables used to predict purchases for column 1 be linear? Otherwise the county average you use won't correctly reflect the average of the individual variables. Furthermore, ideally we'd unify the X variables we use, else it looks fishy for us to use different sets of X variables in different parts of the paper. 
Here is the proposed text that, from the outside, seemed to be the way I would do it:
... where \boldsymbol{X}_{it} is the first seven household covariates presented in Table [tab:DescriptiveStatistics].Specifically, this is household income, years of education, age, household size, race indicators, a married indicator, and employment status.
4. You wrote: “A bi-variate regression of the actual county average log calories purchased per household for each product group (\overline{Y}_{jmt}) on our predicted calories purchased (\hat{Y}_{jmt}) has an R-squared of 0.82.” This seems way too high, right? I've never had X be such a great predictor of product purchases, and some counties don't have that many households in them. Did you accidentally include \delta_{jmt} in the prediction? 

Sorry for all my questions! Thanks for your great work.

**Comment by diamondr** [comment]
Hi Hunt,

Thanks for these follow ups. See below:


   1. You have two nice suggestive tests of the exclusion restriction in
   6.3. It occurs to me that both are really doing the same thing, as I
   suggest in my new proposed text:

*Of course, we cannot test whether the instrument is correlated with
   unobserved tastes. We can, however, present suggestive tests of whether the
   instrument is correlated with tastes predicted by observable
   characteristics. The economic forces that would violate the exclusion
   restriction would likely generate correlations between the instrument and
   both unobserved and predictable tastes. If the instrument is valid, we
   should thus expect to see no relationship between the instrument and
   predictable tastes. We implement two tests, each of which predicts tastes
   in a different way. Great!*
   In light of this close conceptual relationship between the two tests,
   shouldn't we unify the tests a bit more? In Table 4, I see that column 1
   has P on the RHS and does not have county fixed effects, while column 2 has
   P on the LHS and does have county fixed effects but not time effects. I
   think it's helpful to have P on the RHS because \hat{Y} is fitted in column
   1. So what if we:
   a. Unify both columns by putting P on RHS and having j and and m fixed
   effects in all regressions. *Done*
   b. For further unification, why not use county income (continuous)
   instead of 1(above median) in column 2? I think the above median thing was
   a historical relic from when we were graphing something? *Done*
   2. Closely related: what is the justification for having year FEs in
   column 1 but not column 2? I would have thought that both columns have the
   same issue, which is that county income and other taste predictors don't
   change much over time. So I would have thought we shouldn't have t fixed
   effects. *Both regressions now have county, year, and product group FEs.
   I think keeping the year FEs makes sense to ensure any nationwide time
   trends in any of our variables don't drive results.*
   3. Shouldn't the X variables used to predict purchases for column 1 be
   linear? Otherwise the county average you use won't correctly reflect the
   average of the individual variables. Furthermore, ideally we'd unify the X
   variables we use, else it looks fishy for us to use different sets of X
   variables in different parts of the paper. *I have switched it all the
   linear in the Xs your suggest, (although non-linear is totally Kosher too.
   If you had a quadratic in age, you would just plug in the average values of
   age and age squared, not the square of average age.) *
   Here is the proposed text that, from the outside, seemed to be the way I
   would do it:
   ... where \boldsymbol{X}_{it} is the first seven household covariates
   presented in Table [tab:DescriptiveStatistics].Specifically, this is
   household income, years of education, age, household size, race indicators,
   a married indicator, and employment status.
   4. You wrote: “A bi-variate regression of the actual county average log
   calories purchased per household for each product group (\overline{Y}*{jmt})
   on our predicted calories purchased (\hat{Y}*{jmt}) has an R-squared of
   0.82.” This seems way too high, right? I've never had X be such a great
   predictor of product purchases, and some counties don't have that many
   households in them. Did you accidentally include \delta_{jmt} in the
   prediction? *You're right that I was giving the demographics too much
   credit here, since they implicitly contain product group FEs. I have
   demeaned these out first and updated the text.*

**Comment by huntallcott** [comment]
@diamondr thanks for this. Per our emails, I fixed most of the file conflicts on the repo, but I'd be indebted if you would be willing to re-insert those changes into FoodDeserts.lyx. Then I'll take a look. Seems like we are *very* close!

**Comment by moosedube** [comment]
Thank you both for the extra care on this final step of writing and analysis.  Besides appeasing the editor, I think this goes another step towards encouraging others to use this instrument.

Best

JP

Sent from my iPhone

On Apr 10, 2019, at 4:55 AM, Hunt Allcott <notifications@github.com<mailto:notifications@github.com>> wrote:


@diamondr<https://github.com/diamondr> thanks for this. Per our emails, I fixed most of the file conflicts on the repo, but I'd be indebted if you would be willing to re-insert those changes into FoodDeserts.lyx. Then I'll take a look. Seems like we are very close!

**Comment by huntallcott** [comment]
@moosedube @diamondr @handbury @Rahkovsky @mollyschnell ,
Over the last several days, I took another pass through the writeup. Comments/questions below.
1. Larry had asked us to cut five pages, and we were only halfway there. I ruthlessly cut another three pages, mostly off of the structural model sections. For example, I moved section VI.B to the appendix, and I substantially shortened VII.A and VII.B without losing content. @mollyschnell I wonder if you'd be willing to give this a final fresh eye after we resolve the below and also finish #22, just to make sure I didn't screw anything up.
2. JP, you had asked via email, “Is footnote 32 and the discussion around our first means-tested subsidy correct?  In section IV.A we write that the upper bound on a supermarket entry explains at most 0.02*0.44/0.56 = 1.5% of the gap.  But, in footnote 32, we use much smaller numbers, writing that it would only be 0.9%.  This could just be a typo. But I want to confirm that the updated counterfactual was not based on the wrong quantity.” 
I think the footnote is correct. There we are using the point estimate, whereas the text you describe in IV.A is a confidence interval upper bound. I think this is fine and correctly described in the text.

@diamondr, some questions for you: 
3. in 7.3, what is \bar{H} exactly? Is it the Health Index of the median product, as suggested in the notes to Table 6, or is it the Health Index of the median product group? Just wanted to make sure that we are describing it correctly.
4. In Section VI.D describing the beta parameters, I think that the interpretation changed when we went to the new characteristics based on the HEI. I changed the text and wanted to confirm. Specifically, the text had read, "\beta measures the average willingness to pay (WTP) to have a unit of characteristic c instead of a calorie containing no healthy or unhealthy characteristics—for example, a calorie of unsaturated fat." I think this is now wrong due to the different units we’re using. Before, taking away a sugar calorie mechanically meant that you were adding another calorie. Now, I'm not sure that this is the case. Looking at the units, I think that \beta just measures WTP in units of (e.g.) dollars per cup of produce or dollars per ounce of protein. Is the text there OK with you?
5. The equation for the characteristic product seemed to have an error. The  equation sums over s, but s is never defined. 
![image](https://user-images.githubusercontent.com/23505296/55888314-26b5d080-5b7d-11e9-9d18-07b4f678ed2b.png)
I changed the e to s. Does that seem OK as now in the paper?  
6. Are you happy with posting your code publicly for people to see? Here are some things that gave me pause. This is not the biggest deal but I did notice a few things:
  - For tab:IV_exclusion: what if we automatically export from stata? When the tables can be easily created by canned packages, I think that's the best practice in order to minimize transcription errors. I added some code to help do that on line 386 of explore_iv.do; hopefully that might be useful if you decide to go down that path. Otherwise feel free to delete.
  - There appear to be a some old/legacy parameter estimates in Code/Analysis/ModelEstimates/ that I think should instead be deleted from the /Code/ folder, or if they are used for something, perhaps should live in Output/Analysis/ModelEstimates/?
  - Not a huge deal, but there is a lot of duplication in the do files titled estimate_decom_gmm_iv* that might be best addressed using a loop?
  - In general, if you died tomorrow (which I hope won't happen for many many reasons), I would not have the best idea how to replicate this work or what table in the paper comes from what do file. At a minimum, we used to have it set up so that you could run ModelEstimatesSection.do to generate the results. I think this is no longer the case, so I was wondering if you'd be willing to take a look. A nice guideline might be that  all tables are either automatically exported from do files called by AnalysisMasterFile.do, or for bespoke tables, you could describe in the lyx file in red latex comment fields how the table was created. (See, for example, the red latex comment field at the bottom of the very last table in the appendix.)

I'm really sorry for all these questions but just trying to make sure that the paper is replicable and that we don't have any embarrassing screw-ups and/or errata.

**Comment by moosedube** [comment]
Hi Hunt,

Are we sure we want the first paragraph of Appendix D.B in the Appendix?  The moment condition (27) is not obvious at first glance because it does not remove all the mean product group effects. So we use the two types of variation to identify the nutrient preferences. It’s true that we state the moment condition in equation (14), but we do not explain the intuition for that moment.

JP

**Comment by huntallcott** [comment]
@moosedube,
Good question. My opinion was that this detail about the two types of variation is secondary. But I just tracked a change that moves that first para to right after eq (14) and deletes that whole appendix subsection. Take a look and accept or reject?

**Comment by huntallcott** [comment]
@diamondr a quick response today to point 3 [here](https://github.com/huntallcott/FoodDeserts/issues/20#issuecomment-481725503) would be really helpful. I'm trying to finish everything up.

**Comment by huntallcott** [comment]
@diamondr @moosedube @mollyschnell @handbury @Rahkovsky ,
Rebecca finished some final touches to make the MATLAB code most readable. (Thanks Rebecca!) I just took those and made new replication files: dropbox/FoodDeserts/Replication/FoodDeserts_Replication.zip. These are good to post on our websites. 
Closing this issue!

**Comment by moosedube** [comment]
Is there a zip file with the code library to post online?  I am happy to put this on my research page.

JP

**Comment by huntallcott** [comment]
Yes: dropbox/FoodDeserts/Replication/FoodDeserts_Replication.zip.
Let me know if this is not what you meant?
