### ISSUE TITLE
Revise reduced form section

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/FoodDeserts#21]
The goal of this issue is to revise the reduced form sections for the QJE.

There are a few referee questions to answer and footnotes to change, etc. But two analysis questions:
1. Should we control for convenience stores per R2? HA can take the lead on this.
2. @mollyschnell @handbury what do you think about R2's comment 6? Note that Larry Katz's decision letter says "Please pay particular attention to comments 6, 7, and 8 of R2."

cc'ing @diamondr @moosedube @Rahkovsky also.

**Comment by handbury** [comment]
Hi @huntallcott: 

Larry was pretty clear with his directions here so let's follow them.  I also see where R2 is coming from - the within-location analysis certainly doesn't provide as tight a bound with the linear HEI than it was with the other indexes.  How about a footnote/note somewhere to indicate that the point estimates (even the looser structural point estimates) are all within bounds identified by looking within locations, putting the analysis itself in the online appendix or even just referencing these results from our older working paper?

If you agree, we're happy to put this footnote in during the draft revision phase, and look for places to cut/streamline otherwise.  

Best,

Jessie

**Comment by huntallcott** [comment]
OK, this sounds reasonable. I lean slightly toward putting it in online
appendix, but am also OK if you want to take it out entirely. Yes, please
go ahead and implement that removal (including in intro/conclusion?) if you
have time!



-- 

Hunt Allcott

https://sites.google.com/site/allcott/home

**Comment by handbury** [comment]
Hi @huntallcott,

To be honest, I don't remember writing the 4.3 discussion though the tracked changes are telling me that I did! I think that JP might have replaced the old section with this discussion when he went through and did his edits and it got attributed to me in the merge. 

The changes that I made were to cut the old 4.3 (subsec:CrossSection) entirely and add a sentence to the discussion of magnitudes in section 7.1, stating that the estimates reported in this paper are within the LR upper bound reported in HRS.

@moosedube: are you fine with cutting the 4.3 discussion entirely?

**Comment by moosedube** [comment]
Hi Hunt,

I did not make any edits to section 4.3.  I only made edits to the sections 5 onwards and corresponding discussion in intro & conclusion.  I also edited the references to “model free” and “reduced form.”

JP

**Comment by handbury** [comment]
Feel free to delete 4.3 entirely then!

**Comment by huntallcott** [comment]
Great! 
@handbury @moosedube I deleted all of 4.3 and the figure, and I also made sure that the text says "reduced form" instead of "descriptive" per my emails with JP.

**Comment by handbury** [comment]
Thanks @huntallcott! Let @mollyschnell and I know how we can help with the other revisions.
